dist: trusty
sudo: false

language: bash

env:
  - PASS_VERSION=1.7
  - PASS_VERSION=master

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - tree
      - xclip
      - shellcheck

before_script:
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xvf password-store-$PASS_VERSION.tar.xz
  - ln -s password-store-$PASS_VERSION/src/password-store.sh pass
  - export PATH="$PATH:$PWD"

install: true

script:
  - make lint
  - make test
